#!/bin/bash

notify_finished(){
	notify "Backup Finished."
}

make_backup(){
 # $1 - Source folder.
 unison -auto "/run/media/$(whoami)/$1" "$HOME/Backups/$1"
}

# $1 - Drive to backup from
if [ -z "$1" ]; then
# If empty
	make_backup "Paulo_3i3"
	notify_finished
	exit
elif [ "$1" = "-h" ]; then
	echo "Backup - Gut's Utils"
	echo "- A wrapper around UNISON."

	bat -p $HOME/bin/assets/backup.help.zsh
	exit
fi

make_backup
notify_finished
