#!/bin/bash

make_backup(){
 # $1 - Source folder.
 rsync -avz --progress --delete "/run/media/$(whoami)/$1" "$HOME/Backups/"
}

TITLE=$(cat << DELIMITER
Backup - Gut's Utils
- A wrapper around Rsync.
DELIMITER
)

HELP=$(cat << DELIMITER
USAGE:
$ backup [SOURCE_DRIVE_LABEL]

INFO:
This is a driver backup ultility, refer to a drive through it's label.
Source location is: /run/media/$USER/[SOURCE_DRIVE_LABEL]

The backup is stored under /home/$USER/Backups/

# Ideas for the future
Let the user define it's default backuped drives, to backup all them when the user just types $ backup

$ backup -m [--mount], mount the device before starting the backup (if found)
$ backup -u [--unmount], unmount the drive after the backup is done
DELIMITER
)

# $1 - Drive to backup from
if [ -z "$1" ]; then
# If empty
	make_backup "Paulo_3i3"
	notify "Backup Finished."
	exit
elif [ "$1" = "-h" ]; then
	echo -e $TITLE $HELP
	exit
fi

make_backup $1
notify "Backup Finished."
