#!/bin/zsh

###############
## Variables ##
###############

TEXT_EDITOR='nano'

###############
## Functions ##
###############

list_bin() {
	ls --color=auto $HOME/bin
}

print_help() {
	echo "Edit - Gut's Utils"
	echo "Manage your personal scripts."
	echo
	echo "Options:"
	echo
	echo "-h > Display help"
	echo "-p > List your scripts"
	echo "[ \$SCRIPT_NAME ] > edit or creat a script"
	echo "[ nothing ] > 'cd' into /bin"
}

open_or_create_script() {

	# Auto shebang
	## Not useful because I couldn't delete an empty file properly...
	
	#FILE_EXISTS=$(test -e $1 && echo 1)
	#if [ -z $FILE_EXISTS ]; then
	#	touch $1
	#	echo '#!/bin/bash' >> $1
	#fi

	$TEXT_EDITOR $HOME/bin/$1

	chmod +x $HOME/bin/$1

	# A non modified file gets deteled
	## ..Not a good idea actually, I accidentally deleted a useful script.

	# EMPTY=$(test "$(cat $1)" = "#!/bin/bash" && echo 1)
	# if [ $EMPTY ]; then
	#	command rm $HOME/bin/$1
	# fi
}

# The user must commit every changes, this helps him do it.
show_git_status(){
	GIT_STATUS=$(git status --short)
	if [ "$GIT_STATUS" ]; then
		echo "There are changes to commit!"
		git status --short
	fi
}

open_folder(){
	cd $HOME/bin
}

####################
## Handle Options ##
####################

while getopts ":hp" option; do
	case $option in
		h)
			print_help
			exit;;
		p)
			list_bin
			exit;;
		\?)
			echo "Invalid option, use -h for info."
			exit;;
	esac
done

## In case of no option;

if [ -z "$1" ]; then
	open_folder
else
	open_or_create_script $1
fi

show_git_status
