#!/bin/zsh

###############
## Functions ##
###############

list_bin() {
	ls --color=auto $HOME/bin
}

print_help() {
	echo "Edit - Gut's Utils"
	echo "Manage your personal scripts."
	echo
	echo "Options:"
	echo
	echo "-h > Display help"
	echo "-p > List your scripts"
	echo "[ \$SCRIPT_NAME ] > edit or creat a script"
	echo "[ nothing ] > 'cd' into /bin"
}

open_or_create_script() {
	nano $HOME/bin/$1
	chmod +x $HOME/bin/$1
}

####################
## Handle Options ##
####################

while getopts ":hp" option; do
	case $option in
		h)
			print_help
			exit;;
		p)
			list_bin
			exit;;
		\?)
			echo "Invalid option, use -h for info."
			exit;;
	esac
done

## In case of no option;

if [ -z '$1' ]; then
	cd $HOME/bin
else
	open_or_create_script $1
fi
