#!/bin/python

import os, sys

# Suggestion:
# - Possibility for custom message (second argument perhaps?)
# - Time in minutes as default
# - Option -s for seconds
# [x] Message for when the timer starts
# [x] Background process
# - Way to disable the timer in background (closing the termina doesn't do it)

###############
## VARIABLES ##
###############

try:
    TIME = int(sys.argv[1]) * 60
except:
    print('This program recieves only a number as argument.')
    sys.exit(1) # Exit code of 1 indicates error

##########
## MAIN ##
##########

FORMATTED_TIME = TIME / 60
print(f'Timer of {FORMATTED_TIME}m started in background.')
NOTIFY = f'notify-send "Timer of {FORMATTED_TIME}m Finished :D"'

os.system(f'sleep {TIME} && {NOTIFY} &') # The & (Ampersand) on the end makes the command run in background

sys.exit(0)

