#!/bin/python

import os, sys

# Suggestion:
# - Possibility for custom message
# - Time in minutes as default
# - Option -s for seconds
# [x] Message for when the timer starts
# [x] Background process

try:
    TIME = int(sys.argv[1])
except:
    print('This program recieves only a number as argument.')
    # Exit code of 1 indicates error
    sys.exit(1)


FORMATTED_TIME = f'{TIME / 60 :2.2}m' if TIME > 60 else f'{TIME}s'

print(f'Timer of {FORMATTED_TIME} started in background.')
NOTIFY = f'notify-send "Timer of {FORMATTED_TIME} Finished :D"'

os.system(f'sleep {TIME} && {NOTIFY} &') # The & (Ampersand) on the end makes the command run in background

